services:
  db:
    image: postgres:latest
    env_file: .env.example
    ports:
      - 5432
    volumes:
      - ./database/postgres-init:/docker-entrypoint-initdb.d:Z
    healthcheck:
      interval: 10s
      retries: 10
      test: 'pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"'
      timeout: 2s
  app-admin:
    image: nocodb/nocodb:latest
    env_file: .env.example
    ports:
      - 4444
    depends_on:
      db:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.relaxeclimat-app.rule=Host(`relaxeclimat-app.services.d4g.fr`)
      - traefik.http.routers.relaxeclimat-app.entryPoints=webtls
      - traefik.http.routers.relaxeclimat-app.tls=true
      - traefik.docker.network=d4g-internal
      - traefik.http.services.relaxeclimat-app.loadbalancer.server.port=4444
  metabase:
    image: metabase/metabase:latest
    env_file: .env.example
    ports:
      - 3000
    depends_on:
      db:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.relaxeclimat-metabase.rule=Host(`relaxeclimat-metabase.services.d4g.fr`)
      - traefik.http.routers.relaxeclimat-metabase.entryPoints=webtls
      - traefik.http.routers.relaxeclimat-metabase.tls=true
      - traefik.docker.network=d4g-internal
      - traefik.http.services.relaxeclimat-metabase.loadbalancer.server.port=3000
