/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Analyses: () => import('#controllers/analyses_controller'),
  Audiences: () => import('#controllers/audiences_controller'),
  Auth: () => import('#controllers/auth_controller'),
  HealthChecks: () => import('#controllers/health_checks_controller'),
  Home: () => import('#controllers/home_controller'),
  Imports: () => import('#controllers/imports_controller'),
  mappers: {
    TimelineMapper: () => import('#controllers/mappers/timeline_mapper'),
  },
  Webhooks: () => import('#controllers/webhooks_controller'),
}
