/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AudienceSchema extends BaseModel {
  static $columns = [
    'appelDUneDesParties',
    'chefsDePreventionCategorie',
    'chefsDePreventionCategorieSearchable',
    'chefsDePreventionCategorieTextSearchable',
    'chefsDePreventionSousCategorie',
    'commentaireMsde',
    'dateDeDecision',
    'dateDeLAudience',
    'decisionEtPeinesPourLesInfractionsSubiesOuIncidentes',
    'decisionPourLesInfractionsPrincipales',
    'degreDeJuridiction',
    'demandeDesPartiesCiviles',
    'detailDesDommagesEtInterets',
    'detailsDeLaDecisionPourLesInfractionsPrincipales',
    'detailsDesPeinesPourLesInfractionsPrincipales',
    'dommagesEtInterets',
    'extraitDeLaDecision',
    'fondementDeLaRelaxe',
    'fondementDeLaRelaxeSearchable',
    'id',
    'inscriptionAuCasierJudiciaire',
    'jugementOuArret',
    'juridiction',
    'motsCles',
    'nombreDePrevenus',
    'nomsDesPartiesCiviles',
    'numeroDeChambre',
    'partieDeLAppelIncident',
    'partieDeLAppelPrincipal',
    'plaidoirieDeLaDefense',
    'publiee',
    'recitDAudience',
    'referenceDeLaDecision',
    'referenceProcedure',
    'requisitions',
    'resumeDeLAudience',
    'resumeDuJugementOuArret',
    'scoreDeLaGravite',
    'typeDePeinePourLesInfractionsPrincipales',
    'villeDeLAudience',
  ] as const
  $columns = AudienceSchema.$columns
  @column()
  declare appelDUneDesParties: boolean | null
  @column()
  declare chefsDePreventionCategorie: string | null
  @column()
  declare chefsDePreventionCategorieSearchable: any | null
  @column()
  declare chefsDePreventionCategorieTextSearchable: string | null
  @column()
  declare chefsDePreventionSousCategorie: string | null
  @column()
  declare commentaireMsde: string | null
  @column.date()
  declare dateDeDecision: DateTime | null
  @column.date()
  declare dateDeLAudience: DateTime | null
  @column()
  declare decisionEtPeinesPourLesInfractionsSubiesOuIncidentes: string | null
  @column()
  declare decisionPourLesInfractionsPrincipales: string | null
  @column()
  declare degreDeJuridiction: string | null
  @column()
  declare demandeDesPartiesCiviles: string | null
  @column()
  declare detailDesDommagesEtInterets: string | null
  @column()
  declare detailsDeLaDecisionPourLesInfractionsPrincipales: string | null
  @column()
  declare detailsDesPeinesPourLesInfractionsPrincipales: string | null
  @column()
  declare dommagesEtInterets: boolean | null
  @column()
  declare extraitDeLaDecision: string | null
  @column()
  declare fondementDeLaRelaxe: string | null
  @column()
  declare fondementDeLaRelaxeSearchable: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare inscriptionAuCasierJudiciaire: string | null
  @column()
  declare jugementOuArret: string | null
  @column()
  declare juridiction: string | null
  @column()
  declare motsCles: string | null
  @column()
  declare nombreDePrevenus: number | null
  @column()
  declare nomsDesPartiesCiviles: string | null
  @column()
  declare numeroDeChambre: string | null
  @column()
  declare partieDeLAppelIncident: string | null
  @column()
  declare partieDeLAppelPrincipal: string | null
  @column()
  declare plaidoirieDeLaDefense: string | null
  @column()
  declare publiee: boolean
  @column()
  declare recitDAudience: string | null
  @column()
  declare referenceDeLaDecision: string | null
  @column()
  declare referenceProcedure: string | null
  @column()
  declare requisitions: string | null
  @column()
  declare resumeDeLAudience: string | null
  @column()
  declare resumeDuJugementOuArret: string | null
  @column()
  declare scoreDeLaGravite: string | null
  @column()
  declare typeDePeinePourLesInfractionsPrincipales: string | null
  @column()
  declare villeDeLAudience: string | null
}

export class AudiencesPresseArticleSchema extends BaseModel {
  static $columns = ['audienceId', 'presseArticleId'] as const
  $columns = AudiencesPresseArticleSchema.$columns
  @column()
  declare audienceId: number
  @column()
  declare presseArticleId: number
}

export class ConfigurationSchema extends BaseModel {
  static $columns = ['id', 'name', 'value'] as const
  $columns = ConfigurationSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare value: string | null
}

export class DashboardSchema extends BaseModel {
  static $columns = ['id', 'metabaseId', 'publiee', 'titre'] as const
  $columns = DashboardSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare metabaseId: number
  @column()
  declare publiee: boolean
  @column()
  declare titre: string
}

export class PresseArticleSchema extends BaseModel {
  static $columns = ['id', 'titre', 'url'] as const
  $columns = PresseArticleSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare titre: string
  @column()
  declare url: string | null
}

export class ProcedureSchema extends BaseModel {
  static $columns = [
    'collectifDActionOuLutte',
    'collectifDActionOuLutteSearchable',
    'dateDesFaits',
    'faitsConcis',
    'faitsDetailles',
    'faitsDetaillesSearchable',
    'id',
    'poursuites',
    'publiee',
    'referenceProcedure',
    'titre',
    'titreSearchable',
  ] as const
  $columns = ProcedureSchema.$columns
  @column()
  declare collectifDActionOuLutte: string | null
  @column()
  declare collectifDActionOuLutteSearchable: any | null
  @column.date()
  declare dateDesFaits: DateTime | null
  @column()
  declare faitsConcis: string | null
  @column()
  declare faitsDetailles: string | null
  @column()
  declare faitsDetaillesSearchable: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare poursuites: string | null
  @column()
  declare publiee: boolean
  @column()
  declare referenceProcedure: string
  @column()
  declare titre: string
  @column()
  declare titreSearchable: string | null
}

export class ProceduresPresseArticleSchema extends BaseModel {
  static $columns = ['presseArticleId', 'referenceProcedure'] as const
  $columns = ProceduresPresseArticleSchema.$columns
  @column()
  declare presseArticleId: number
  @column()
  declare referenceProcedure: string
}

export class RememberMeTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'hash', 'id', 'tokenableId', 'updatedAt'] as const
  $columns = RememberMeTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UtilisateurSchema extends BaseModel {
  static $columns = [
    'approved',
    'createdAt',
    'email',
    'id',
    'motivation',
    'password',
    'passwordToken',
    'passwordTokenCreatedAt',
    'updatedAt',
  ] as const
  $columns = UtilisateurSchema.$columns
  @column()
  declare approved: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare motivation: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare passwordToken: string | null
  @column.dateTime()
  declare passwordTokenCreatedAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
